version: '3.9'

services:

  db:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    volumes:
      - ./docker-volumes/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER:     postgres
      POSTGRES_PASSWORD: postgres
